name: simple_rc4
description: Yet another RC4 cryptor that encodes/decodes bytes and UTF8 strings.
version: 0.1.6
homepage: https://github.com/zonble/simple_rc4_dart
author: zonble <zonble@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"
dev_dependencies:
  test: ^1.9.4
  pedantic: ^1.9.0
