name: simple_rc4
description: Yet another RC4 encryptor
version: 0.1.1
homepage: https://github.com/zonble/simple_rc4_dart
author: zonble <zonble@gmail.com>
environment:
  sdk: ">=2.0.0 <3.0.0"
dev_dependencies:
  test: ^1.0.0
